config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: :destroy
  root to: "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "This movie is already in the list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # before_action :set_list
  # before_action :set_bookmark, only: [:destroy]

  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list), notice: 'Bookmark was successfully added.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.id), notice: 'Bookmark was successfully removed.'
  end


  private

  # def set_list
  #   @list = List.find(params[:list_id])
  # end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Add Bookmark</h1>


<div class="col-4 my-3 bg-light h-100 p-3">
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.association :movie %>
        <%= f.input :comment %>
        <%= f.submit "Add a movie", class: "btn btn-primary" %>
      <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1 class="mb-4">All Lists</h1>

<div class="list-group mb-3">
  <% @lists.each do |list| %>
    <%= link_to list.name, list_path(list), class: 'list-group-item list-group-item-action' %>
  <% end %>
</div>

<div class="text-end">
  <%= link_to 'Create New List', new_list_path, class: 'btn btn-primary' %>
</div>

app/views/lists/new.html.erb
<h1>Create a New List</h1>
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name, class: "mb-4", required: false %>
  <div class="mt-3">
    <%= f.button :submit, "Create list", class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to "Back to Lists", lists_path %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<h3>Movies in this list</h3>
<ul>
  <% @bookmarks.each do |bookmark| %>
    <li><%= bookmark.movie.title %> - <%= bookmark.comment %>
      <form action="<%= list_bookmarks_path(@list) %>" method="post" class="d-inline">
        <%# <input type="hidden" name="_method" value="delete">
        <button type="submit" class="btn btn-warning btn-sm">Remove</button> %>
        <%= link_to "Delete", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you Sure?"} %>
      </form>
    </li>
  <% end %>
</ul>
<a href="<%= new_list_bookmark_path(@list) %>">Add Bookmark</a>


<%= link_to "Back to Lists", lists_path %>